### Testes de Métodos
#
###
# Requisitando com Método GET
GET  http://127.0.0.1:8000/contato/
Content-Type: application/json

###
# Requisitando com Método GET
GET  http://127.0.0.1:8000/
Content-Type: application/json

###
# Requisitando com Método PUT
PUT  http://127.0.0.1:8000/contato/
Content-Type: application/json

###
# Requisitando com Método POST
POST  http://127.0.0.1:8000/contato/
Content-Type: application/json

###
# Requisitando com Método DELETE
DELETE  http://127.0.0.1:8000/contato/
Content-Type: application/json